version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mosquitto
      - mongo

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  test:
      build: .
      env_file:
        - .env
      depends_on:
        - mosquitto
        - mongo
      command: pytest